CREATE TABLE HISTORICO_COVID_POR_ESTADOS (
    DATA_REFERENCIA DATE,
    STATE VARCHAR(8),
    DEATHS INT,
    TOTAL_CASES INT,
    NEW_DEATHS INT,
    NEW_CASES INT
);


CREATE TABLE HISTORICO_COVID_TOTAIS (
    DATA_REFERENCIA DATE,
    DEATHS INT,
    TOTAL_CASES INT,
    NEW_DEATHS INT,
    NEW_CASES INT
);


CREATE TABLE TOTAL_REQUESTS (
    DATA_REFERENCIA DATE,
    QUANTIDADE INT,
    ENDPOINT VARCHAR(255)
);


