CREATE TABLE HISTORICO_COVID_POR_ESTADOS (
    DATA_REFERENCIA DATE,
    STATE VARCHAR(8),
    NEW_DEATHS INT,
    NEW_CASES INT
);


CREATE TABLE TOTAL_REQUESTS (
    DATA_REFERENCIA DATE,
    QUANTIDADE INT,
    ENDPOINT VARCHAR(255)
);


